#!/bin/bash
case $1 in
 
on)
git config --global http.proxy 'http://'$2 
git config --global https.proxy 'http://'$2
;;
 
off)
git config --global --unset http.proxy
git config --global --unset https.proxy
;;
 
status)
git config --get http.proxy
git config --get https.proxy
;;
esac
